//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scenes/Chertolet/Files/ChertoletControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ChertoletControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ChertoletControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ChertoletControls"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""e70b6012-1cc2-4f15-a1b8-2d6bfbeaa856"",
            ""actions"": [
                {
                    ""name"": ""Impulse"",
                    ""type"": ""Button"",
                    ""id"": ""00441e31-03c4-4cb3-ba54-736b308d0856"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Simbit"",
                    ""type"": ""Button"",
                    ""id"": ""ab3227ad-de07-49d3-bc37-d54bfa5c56a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""6f70a01c-fab7-4127-b378-1531fafbee2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""031e4ba3-95b1-479b-8af3-dfe1374a952a"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Impulse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6ff5a41-b841-4ab0-b982-8693df795af5"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Impulse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e2e1c8b-255a-459e-9046-acaa859ddae2"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Simbit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0695092-6976-4349-8795-3a02818bd080"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Wearables"",
            ""id"": ""3a6e5ab3-2750-4c0c-824d-f859eaa7fce9"",
            ""actions"": [
                {
                    ""name"": ""Wearable1"",
                    ""type"": ""Button"",
                    ""id"": ""8743d1f7-75f2-4477-a357-51f9757c9b8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wearable2"",
                    ""type"": ""Button"",
                    ""id"": ""995c6992-7b48-4764-83a7-94a80cc3cfcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wearable3"",
                    ""type"": ""Button"",
                    ""id"": ""0a51bad0-4183-4416-bb57-d31f7a840bcb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wearable4"",
                    ""type"": ""Button"",
                    ""id"": ""bc8c9a25-6e46-4f3e-8dff-1907cb992d89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""72cd9333-1366-4b6b-a97f-2364a50c514d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a991477-4f9f-4efc-b07f-221d57fb9a00"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f7fdbae-49d0-4df3-8a46-ce6381d98ee5"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b60e73ea-855c-4bab-9e37-559c60c63f63"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74220bcd-1f7f-48a7-bb3c-f50305a07425"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7047e595-a6c5-4421-b0b5-6d6c71609333"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7e8a74f-61b3-40f6-ba08-938c3da8bdb4"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01b75e66-7c4e-450e-a398-f12e9d6d4255"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_Impulse = m_GamePlay.FindAction("Impulse", throwIfNotFound: true);
        m_GamePlay_Simbit = m_GamePlay.FindAction("Simbit", throwIfNotFound: true);
        m_GamePlay_Exit = m_GamePlay.FindAction("Exit", throwIfNotFound: true);
        // Wearables
        m_Wearables = asset.FindActionMap("Wearables", throwIfNotFound: true);
        m_Wearables_Wearable1 = m_Wearables.FindAction("Wearable1", throwIfNotFound: true);
        m_Wearables_Wearable2 = m_Wearables.FindAction("Wearable2", throwIfNotFound: true);
        m_Wearables_Wearable3 = m_Wearables.FindAction("Wearable3", throwIfNotFound: true);
        m_Wearables_Wearable4 = m_Wearables.FindAction("Wearable4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private List<IGamePlayActions> m_GamePlayActionsCallbackInterfaces = new List<IGamePlayActions>();
    private readonly InputAction m_GamePlay_Impulse;
    private readonly InputAction m_GamePlay_Simbit;
    private readonly InputAction m_GamePlay_Exit;
    public struct GamePlayActions
    {
        private @ChertoletControls m_Wrapper;
        public GamePlayActions(@ChertoletControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Impulse => m_Wrapper.m_GamePlay_Impulse;
        public InputAction @Simbit => m_Wrapper.m_GamePlay_Simbit;
        public InputAction @Exit => m_Wrapper.m_GamePlay_Exit;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void AddCallbacks(IGamePlayActions instance)
        {
            if (instance == null || m_Wrapper.m_GamePlayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Add(instance);
            @Impulse.started += instance.OnImpulse;
            @Impulse.performed += instance.OnImpulse;
            @Impulse.canceled += instance.OnImpulse;
            @Simbit.started += instance.OnSimbit;
            @Simbit.performed += instance.OnSimbit;
            @Simbit.canceled += instance.OnSimbit;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
        }

        private void UnregisterCallbacks(IGamePlayActions instance)
        {
            @Impulse.started -= instance.OnImpulse;
            @Impulse.performed -= instance.OnImpulse;
            @Impulse.canceled -= instance.OnImpulse;
            @Simbit.started -= instance.OnSimbit;
            @Simbit.performed -= instance.OnSimbit;
            @Simbit.canceled -= instance.OnSimbit;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
        }

        public void RemoveCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamePlayActions instance)
        {
            foreach (var item in m_Wrapper.m_GamePlayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);

    // Wearables
    private readonly InputActionMap m_Wearables;
    private List<IWearablesActions> m_WearablesActionsCallbackInterfaces = new List<IWearablesActions>();
    private readonly InputAction m_Wearables_Wearable1;
    private readonly InputAction m_Wearables_Wearable2;
    private readonly InputAction m_Wearables_Wearable3;
    private readonly InputAction m_Wearables_Wearable4;
    public struct WearablesActions
    {
        private @ChertoletControls m_Wrapper;
        public WearablesActions(@ChertoletControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Wearable1 => m_Wrapper.m_Wearables_Wearable1;
        public InputAction @Wearable2 => m_Wrapper.m_Wearables_Wearable2;
        public InputAction @Wearable3 => m_Wrapper.m_Wearables_Wearable3;
        public InputAction @Wearable4 => m_Wrapper.m_Wearables_Wearable4;
        public InputActionMap Get() { return m_Wrapper.m_Wearables; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WearablesActions set) { return set.Get(); }
        public void AddCallbacks(IWearablesActions instance)
        {
            if (instance == null || m_Wrapper.m_WearablesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WearablesActionsCallbackInterfaces.Add(instance);
            @Wearable1.started += instance.OnWearable1;
            @Wearable1.performed += instance.OnWearable1;
            @Wearable1.canceled += instance.OnWearable1;
            @Wearable2.started += instance.OnWearable2;
            @Wearable2.performed += instance.OnWearable2;
            @Wearable2.canceled += instance.OnWearable2;
            @Wearable3.started += instance.OnWearable3;
            @Wearable3.performed += instance.OnWearable3;
            @Wearable3.canceled += instance.OnWearable3;
            @Wearable4.started += instance.OnWearable4;
            @Wearable4.performed += instance.OnWearable4;
            @Wearable4.canceled += instance.OnWearable4;
        }

        private void UnregisterCallbacks(IWearablesActions instance)
        {
            @Wearable1.started -= instance.OnWearable1;
            @Wearable1.performed -= instance.OnWearable1;
            @Wearable1.canceled -= instance.OnWearable1;
            @Wearable2.started -= instance.OnWearable2;
            @Wearable2.performed -= instance.OnWearable2;
            @Wearable2.canceled -= instance.OnWearable2;
            @Wearable3.started -= instance.OnWearable3;
            @Wearable3.performed -= instance.OnWearable3;
            @Wearable3.canceled -= instance.OnWearable3;
            @Wearable4.started -= instance.OnWearable4;
            @Wearable4.performed -= instance.OnWearable4;
            @Wearable4.canceled -= instance.OnWearable4;
        }

        public void RemoveCallbacks(IWearablesActions instance)
        {
            if (m_Wrapper.m_WearablesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWearablesActions instance)
        {
            foreach (var item in m_Wrapper.m_WearablesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WearablesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WearablesActions @Wearables => new WearablesActions(this);
    public interface IGamePlayActions
    {
        void OnImpulse(InputAction.CallbackContext context);
        void OnSimbit(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
    }
    public interface IWearablesActions
    {
        void OnWearable1(InputAction.CallbackContext context);
        void OnWearable2(InputAction.CallbackContext context);
        void OnWearable3(InputAction.CallbackContext context);
        void OnWearable4(InputAction.CallbackContext context);
    }
}
