//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scenes/Menu/Files/WearablesControlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @WearablesControlls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @WearablesControlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""WearablesControlls"",
    ""maps"": [
        {
            ""name"": ""Wearables"",
            ""id"": ""8773ce88-d9da-488d-9412-ec4d060f2058"",
            ""actions"": [
                {
                    ""name"": ""Wearable1"",
                    ""type"": ""Button"",
                    ""id"": ""80ba0a9e-744c-422d-b2bb-85379602b38a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wearable2"",
                    ""type"": ""Button"",
                    ""id"": ""571ecfeb-97e1-4fce-9366-9a3c4d26338c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wearable3"",
                    ""type"": ""Button"",
                    ""id"": ""1e87b85c-11ed-4455-8338-48c70a2d75f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wearable4"",
                    ""type"": ""Button"",
                    ""id"": ""2e46b5db-56bf-4eec-aacd-59814e21efd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""14c6290e-cb5b-4e61-a01e-122af11a5276"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a3f6246-4576-49fd-b945-119f06533df2"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86c4c41a-a4d6-4fa7-9c1f-b14b611f70cb"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d70acf97-6185-4a76-856a-440c387bfa29"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21dbabe8-7dba-466d-a3bf-63b335dd749a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f19cb6c-daea-4b9f-95df-00a427279c36"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74a8a831-b0f7-4d01-a8ae-72dc5b6c094e"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ab5d5df-f368-493c-8b76-3aabb46a863a"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wearable4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Wearables
        m_Wearables = asset.FindActionMap("Wearables", throwIfNotFound: true);
        m_Wearables_Wearable1 = m_Wearables.FindAction("Wearable1", throwIfNotFound: true);
        m_Wearables_Wearable2 = m_Wearables.FindAction("Wearable2", throwIfNotFound: true);
        m_Wearables_Wearable3 = m_Wearables.FindAction("Wearable3", throwIfNotFound: true);
        m_Wearables_Wearable4 = m_Wearables.FindAction("Wearable4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Wearables
    private readonly InputActionMap m_Wearables;
    private List<IWearablesActions> m_WearablesActionsCallbackInterfaces = new List<IWearablesActions>();
    private readonly InputAction m_Wearables_Wearable1;
    private readonly InputAction m_Wearables_Wearable2;
    private readonly InputAction m_Wearables_Wearable3;
    private readonly InputAction m_Wearables_Wearable4;
    public struct WearablesActions
    {
        private @WearablesControlls m_Wrapper;
        public WearablesActions(@WearablesControlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Wearable1 => m_Wrapper.m_Wearables_Wearable1;
        public InputAction @Wearable2 => m_Wrapper.m_Wearables_Wearable2;
        public InputAction @Wearable3 => m_Wrapper.m_Wearables_Wearable3;
        public InputAction @Wearable4 => m_Wrapper.m_Wearables_Wearable4;
        public InputActionMap Get() { return m_Wrapper.m_Wearables; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WearablesActions set) { return set.Get(); }
        public void AddCallbacks(IWearablesActions instance)
        {
            if (instance == null || m_Wrapper.m_WearablesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WearablesActionsCallbackInterfaces.Add(instance);
            @Wearable1.started += instance.OnWearable1;
            @Wearable1.performed += instance.OnWearable1;
            @Wearable1.canceled += instance.OnWearable1;
            @Wearable2.started += instance.OnWearable2;
            @Wearable2.performed += instance.OnWearable2;
            @Wearable2.canceled += instance.OnWearable2;
            @Wearable3.started += instance.OnWearable3;
            @Wearable3.performed += instance.OnWearable3;
            @Wearable3.canceled += instance.OnWearable3;
            @Wearable4.started += instance.OnWearable4;
            @Wearable4.performed += instance.OnWearable4;
            @Wearable4.canceled += instance.OnWearable4;
        }

        private void UnregisterCallbacks(IWearablesActions instance)
        {
            @Wearable1.started -= instance.OnWearable1;
            @Wearable1.performed -= instance.OnWearable1;
            @Wearable1.canceled -= instance.OnWearable1;
            @Wearable2.started -= instance.OnWearable2;
            @Wearable2.performed -= instance.OnWearable2;
            @Wearable2.canceled -= instance.OnWearable2;
            @Wearable3.started -= instance.OnWearable3;
            @Wearable3.performed -= instance.OnWearable3;
            @Wearable3.canceled -= instance.OnWearable3;
            @Wearable4.started -= instance.OnWearable4;
            @Wearable4.performed -= instance.OnWearable4;
            @Wearable4.canceled -= instance.OnWearable4;
        }

        public void RemoveCallbacks(IWearablesActions instance)
        {
            if (m_Wrapper.m_WearablesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWearablesActions instance)
        {
            foreach (var item in m_Wrapper.m_WearablesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WearablesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WearablesActions @Wearables => new WearablesActions(this);
    public interface IWearablesActions
    {
        void OnWearable1(InputAction.CallbackContext context);
        void OnWearable2(InputAction.CallbackContext context);
        void OnWearable3(InputAction.CallbackContext context);
        void OnWearable4(InputAction.CallbackContext context);
    }
}
