//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scenes/InDev/Ribbit'sRealm/RibbitsDoc/Coding/Input/RibbitsRealmInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RibbitsRealmInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RibbitsRealmInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RibbitsRealmInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""ad7616e4-eb86-4856-a4a2-bcdfde3c64e3"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""cf945d8d-acf6-4bbb-98b8-69bb06abae6c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""80eed50a-063b-4bae-9b3d-07cd955ea0c5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a7c7f9df-9f64-4dda-bac1-fd6fb0b7234d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""c193a2a3-28a6-4995-a372-68b66705e264"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""658b3357-c7bd-4a95-b22e-bcfec652e9fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Punch"",
                    ""type"": ""Button"",
                    ""id"": ""ac73f99b-6dca-4fa6-8428-343b64e3de7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Place"",
                    ""type"": ""Button"",
                    ""id"": ""ae85d1ad-daec-4396-951f-112e4d5510cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e0c1d0af-4fc6-4d03-b42b-cd0306532bc1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""afc6200b-e382-4544-baf9-ed1bd6a7d243"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""84ae79ce-fc9e-4b5d-89a7-81b12b9b22b5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bc27f002-d7a0-4073-84f6-a0e2bcfbbf6a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""40b8311c-cf6c-4146-8c8d-038c45c40417"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7e3b0817-5b2d-4d98-bd9b-2f1d18c72225"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b0fa3ff-09cf-4d77-af35-3dc057f0deca"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""060f4ee0-1c40-4ff3-819d-52840be8db0a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""594895e6-0264-4038-bd55-dda47363446f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efc5cb20-8340-41c8-9aab-a66c4cb62b49"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f01c893e-91e7-4f4e-866a-d655904d1cb0"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c41b0f8-0c11-4dc0-83a0-003cd09a1372"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55076a46-89ba-4467-b338-f51f685d72c7"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""100248c6-adf4-4477-aec7-0c1836ab60d7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f66642e9-52f3-488c-be71-118dc6ca5271"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Punch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa93db0b-403a-4259-bf67-0b222a61f92c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Place"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Hotbar"",
            ""id"": ""713e1275-6fc6-4296-b362-7630dabadd25"",
            ""actions"": [
                {
                    ""name"": ""FirstSlot"",
                    ""type"": ""Button"",
                    ""id"": ""9871fe40-d74c-475d-9803-d12e22fb0ad6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondSlot"",
                    ""type"": ""Button"",
                    ""id"": ""6ee0f114-438a-411b-9fa3-9d5448393ac7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdSlot"",
                    ""type"": ""Button"",
                    ""id"": ""55c7cd7a-9bc3-4c27-b4b6-0389bb23ddbe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4slot"",
                    ""type"": ""Button"",
                    ""id"": ""06de0f00-e819-4b03-bb5a-c2bd6d3c54f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""5slot"",
                    ""type"": ""Button"",
                    ""id"": ""1dc2aaa8-af43-40c0-b15c-b2e0c5662fea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""6slot"",
                    ""type"": ""Button"",
                    ""id"": ""fe781e74-430c-49f7-b9d0-f2dae59627a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""7slot"",
                    ""type"": ""Button"",
                    ""id"": ""734265ca-231a-491b-a73b-261e302e8b7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""8slot"",
                    ""type"": ""Button"",
                    ""id"": ""eeac4727-77e9-4541-92ed-2933c205f92c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""9slot"",
                    ""type"": ""Button"",
                    ""id"": ""3fc854b8-67a2-4596-ac44-cd6b33bdb134"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3a6e5050-0a96-406e-b02c-011b8bd8bbbe"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e103210-cdda-4c8c-b8a0-05094d32152c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""914db13f-fc3d-4716-9328-05b0fdfa0f91"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2df8d864-c482-433d-aaf2-bbbe636d6ca3"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84ccf8e0-d0ab-4908-abac-0f7f626be897"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42dff7fe-aec6-4a27-82ad-b17b2dea1054"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36e8f3bf-dca7-4731-9789-aa173fa5dc08"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d71db15-661f-48e5-8e17-5e4c3a8d5305"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65c08a5c-5cb5-49ac-8498-46114257e787"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""9slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Punch = m_Player.FindAction("Punch", throwIfNotFound: true);
        m_Player_Place = m_Player.FindAction("Place", throwIfNotFound: true);
        // Hotbar
        m_Hotbar = asset.FindActionMap("Hotbar", throwIfNotFound: true);
        m_Hotbar_FirstSlot = m_Hotbar.FindAction("FirstSlot", throwIfNotFound: true);
        m_Hotbar_SecondSlot = m_Hotbar.FindAction("SecondSlot", throwIfNotFound: true);
        m_Hotbar_ThirdSlot = m_Hotbar.FindAction("ThirdSlot", throwIfNotFound: true);
        m_Hotbar__4slot = m_Hotbar.FindAction("4slot", throwIfNotFound: true);
        m_Hotbar__5slot = m_Hotbar.FindAction("5slot", throwIfNotFound: true);
        m_Hotbar__6slot = m_Hotbar.FindAction("6slot", throwIfNotFound: true);
        m_Hotbar__7slot = m_Hotbar.FindAction("7slot", throwIfNotFound: true);
        m_Hotbar__8slot = m_Hotbar.FindAction("8slot", throwIfNotFound: true);
        m_Hotbar__9slot = m_Hotbar.FindAction("9slot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Punch;
    private readonly InputAction m_Player_Place;
    public struct PlayerActions
    {
        private @RibbitsRealmInput m_Wrapper;
        public PlayerActions(@RibbitsRealmInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Punch => m_Wrapper.m_Player_Punch;
        public InputAction @Place => m_Wrapper.m_Player_Place;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Punch.started += instance.OnPunch;
            @Punch.performed += instance.OnPunch;
            @Punch.canceled += instance.OnPunch;
            @Place.started += instance.OnPlace;
            @Place.performed += instance.OnPlace;
            @Place.canceled += instance.OnPlace;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Punch.started -= instance.OnPunch;
            @Punch.performed -= instance.OnPunch;
            @Punch.canceled -= instance.OnPunch;
            @Place.started -= instance.OnPlace;
            @Place.performed -= instance.OnPlace;
            @Place.canceled -= instance.OnPlace;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Hotbar
    private readonly InputActionMap m_Hotbar;
    private List<IHotbarActions> m_HotbarActionsCallbackInterfaces = new List<IHotbarActions>();
    private readonly InputAction m_Hotbar_FirstSlot;
    private readonly InputAction m_Hotbar_SecondSlot;
    private readonly InputAction m_Hotbar_ThirdSlot;
    private readonly InputAction m_Hotbar__4slot;
    private readonly InputAction m_Hotbar__5slot;
    private readonly InputAction m_Hotbar__6slot;
    private readonly InputAction m_Hotbar__7slot;
    private readonly InputAction m_Hotbar__8slot;
    private readonly InputAction m_Hotbar__9slot;
    public struct HotbarActions
    {
        private @RibbitsRealmInput m_Wrapper;
        public HotbarActions(@RibbitsRealmInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirstSlot => m_Wrapper.m_Hotbar_FirstSlot;
        public InputAction @SecondSlot => m_Wrapper.m_Hotbar_SecondSlot;
        public InputAction @ThirdSlot => m_Wrapper.m_Hotbar_ThirdSlot;
        public InputAction @_4slot => m_Wrapper.m_Hotbar__4slot;
        public InputAction @_5slot => m_Wrapper.m_Hotbar__5slot;
        public InputAction @_6slot => m_Wrapper.m_Hotbar__6slot;
        public InputAction @_7slot => m_Wrapper.m_Hotbar__7slot;
        public InputAction @_8slot => m_Wrapper.m_Hotbar__8slot;
        public InputAction @_9slot => m_Wrapper.m_Hotbar__9slot;
        public InputActionMap Get() { return m_Wrapper.m_Hotbar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HotbarActions set) { return set.Get(); }
        public void AddCallbacks(IHotbarActions instance)
        {
            if (instance == null || m_Wrapper.m_HotbarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HotbarActionsCallbackInterfaces.Add(instance);
            @FirstSlot.started += instance.OnFirstSlot;
            @FirstSlot.performed += instance.OnFirstSlot;
            @FirstSlot.canceled += instance.OnFirstSlot;
            @SecondSlot.started += instance.OnSecondSlot;
            @SecondSlot.performed += instance.OnSecondSlot;
            @SecondSlot.canceled += instance.OnSecondSlot;
            @ThirdSlot.started += instance.OnThirdSlot;
            @ThirdSlot.performed += instance.OnThirdSlot;
            @ThirdSlot.canceled += instance.OnThirdSlot;
            @_4slot.started += instance.On_4slot;
            @_4slot.performed += instance.On_4slot;
            @_4slot.canceled += instance.On_4slot;
            @_5slot.started += instance.On_5slot;
            @_5slot.performed += instance.On_5slot;
            @_5slot.canceled += instance.On_5slot;
            @_6slot.started += instance.On_6slot;
            @_6slot.performed += instance.On_6slot;
            @_6slot.canceled += instance.On_6slot;
            @_7slot.started += instance.On_7slot;
            @_7slot.performed += instance.On_7slot;
            @_7slot.canceled += instance.On_7slot;
            @_8slot.started += instance.On_8slot;
            @_8slot.performed += instance.On_8slot;
            @_8slot.canceled += instance.On_8slot;
            @_9slot.started += instance.On_9slot;
            @_9slot.performed += instance.On_9slot;
            @_9slot.canceled += instance.On_9slot;
        }

        private void UnregisterCallbacks(IHotbarActions instance)
        {
            @FirstSlot.started -= instance.OnFirstSlot;
            @FirstSlot.performed -= instance.OnFirstSlot;
            @FirstSlot.canceled -= instance.OnFirstSlot;
            @SecondSlot.started -= instance.OnSecondSlot;
            @SecondSlot.performed -= instance.OnSecondSlot;
            @SecondSlot.canceled -= instance.OnSecondSlot;
            @ThirdSlot.started -= instance.OnThirdSlot;
            @ThirdSlot.performed -= instance.OnThirdSlot;
            @ThirdSlot.canceled -= instance.OnThirdSlot;
            @_4slot.started -= instance.On_4slot;
            @_4slot.performed -= instance.On_4slot;
            @_4slot.canceled -= instance.On_4slot;
            @_5slot.started -= instance.On_5slot;
            @_5slot.performed -= instance.On_5slot;
            @_5slot.canceled -= instance.On_5slot;
            @_6slot.started -= instance.On_6slot;
            @_6slot.performed -= instance.On_6slot;
            @_6slot.canceled -= instance.On_6slot;
            @_7slot.started -= instance.On_7slot;
            @_7slot.performed -= instance.On_7slot;
            @_7slot.canceled -= instance.On_7slot;
            @_8slot.started -= instance.On_8slot;
            @_8slot.performed -= instance.On_8slot;
            @_8slot.canceled -= instance.On_8slot;
            @_9slot.started -= instance.On_9slot;
            @_9slot.performed -= instance.On_9slot;
            @_9slot.canceled -= instance.On_9slot;
        }

        public void RemoveCallbacks(IHotbarActions instance)
        {
            if (m_Wrapper.m_HotbarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHotbarActions instance)
        {
            foreach (var item in m_Wrapper.m_HotbarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HotbarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HotbarActions @Hotbar => new HotbarActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnPunch(InputAction.CallbackContext context);
        void OnPlace(InputAction.CallbackContext context);
    }
    public interface IHotbarActions
    {
        void OnFirstSlot(InputAction.CallbackContext context);
        void OnSecondSlot(InputAction.CallbackContext context);
        void OnThirdSlot(InputAction.CallbackContext context);
        void On_4slot(InputAction.CallbackContext context);
        void On_5slot(InputAction.CallbackContext context);
        void On_6slot(InputAction.CallbackContext context);
        void On_7slot(InputAction.CallbackContext context);
        void On_8slot(InputAction.CallbackContext context);
        void On_9slot(InputAction.CallbackContext context);
    }
}
